language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npx vuepress build blog

after_script:
  - cd blog/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push --force --quiet "https://${GH_Token}@${GIT_PAGE_REF}" master:master

env:
  global:
    - GIT_PAGE_REF: github.com/Limsanity/Limsanity.github.io.git